version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: volunteer_postgres
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: volunteer_server
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=project;Username=postgres;Password=postgres
    depends_on:
      - postgres

volumes:
  postgres_data: